### ISSUE TITLE
Magnum Torch not working

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/AMDIForge#2]
From here:
https://github.com/GTNewHorizons/NewHorizons/issues/3204#issuecomment-414447545

Looks like when AMDIForge is installed on the server side the torches don't work... Dream says it controls spawns in some way so I guess it should be left on our servers..

**Comment by draknyte1** [comment]
It's used explicitly on Delta and Epsilon. Unless you configure it yourself, it's not doing anything useful afaik.
